config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get	 '/club',    to: 'static_pages#club'
  resources :users
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def club
  	@users = User.all

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def club
    @user = User.all
  end

   def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #669999;">
  <%= link_to "Private Club", root_path, :class => "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <% if logged_in? %>
        <li class="nav-item active"><%= link_to "Club", club_path, :class => "nav-link"%></li>   
        <li class="nav-item active"><%= link_to "Profil", current_user, :class => "nav-link"%></li>
        <li class="nav-item active"><%= link_to "Déconnexion", logout_path, method: :delete, :class => "nav-link"%></li>
           
        </li>

        <% else %>
          <li class="nav-item active"><%= link_to "Connexion", login_path, :class => "nav-link"%></li>
          <li class="nav-item active"><%= link_to "Inscription", signup_path, :class => "nav-link"%></li>

      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "/layouts/header" %>
    <div class="container">
    <div><%= flash[:danger] %></div>
    <br><br>
    <%= yield %>
    </div>

    <!-- JS BOOTSTRAP -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/club.html.erb
<h1>PAGE DU CLUB</h1>

<% if logged_in? %>

<table style="width:100%">
	<tr>
      <th>Last_name</th>
      <th>First_name</th>
      <th>Email</th>
	</tr>
<% @users.each do |user| %>
 
	<tr>

		<td><%= user.last_name %></td>
		<td><%= user.first_name %></td>
		<td><%= user.email %></td>
	</tr>

<% end %>

	<% else %>
  You need to be logged in to access this content. <br><br>
  <%= link_to "Sign up", signup_path, class: "btn btn btn-primary" %>     <%= link_to "Log in", login_path, class: "btn btn-primary" %>

  <% end %>

app/views/static_pages/index.html.erb
<h1>Private Club</h1>

<% if logged_in? %>
	<h2>Bonjour <%= @current_user.first_name %> !</h2>
	<br>
	<%= link_to "Page du club", club_path, class: "btn btn-primary" %>
<% else %>
	<h2>Bonjour, veuillez vous connecter</h2>
	<br>
	<%= link_to "Connexion", login_path, class: "btn btn-primary" %>
	<%= link_to "S'incrire", signup_path, class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for (@user) do |f| %>

      <div class='form-group'>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
      </div>

      <div class='form-group'>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
      </div>

      <div class='form-group'>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class='form-group'>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
  	  </div>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
<h1>Profil</h1>
	<h3>Prénom : <%= @current_user.first_name %></h3>
	<h3>Nom : <%= @current_user.last_name %></h3>
	<h3>Email : <%= @current_user.email %></h3>
<% end %>